// Generated by gencpp from file gpd_grasp_msgs/GraspConfig.msg
// DO NOT EDIT!


#ifndef GPD_GRASP_MSGS_MESSAGE_GRASPCONFIG_H
#define GPD_GRASP_MSGS_MESSAGE_GRASPCONFIG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Point.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>

namespace gpd_grasp_msgs
{
template <class ContainerAllocator>
struct GraspConfig_
{
  typedef GraspConfig_<ContainerAllocator> Type;

  GraspConfig_()
    : bottom()
    , top()
    , surface()
    , approach()
    , binormal()
    , axis()
    , sample()
    , width()
    , score()  {
    }
  GraspConfig_(const ContainerAllocator& _alloc)
    : bottom(_alloc)
    , top(_alloc)
    , surface(_alloc)
    , approach(_alloc)
    , binormal(_alloc)
    , axis(_alloc)
    , sample(_alloc)
    , width(_alloc)
    , score(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _bottom_type;
  _bottom_type bottom;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _top_type;
  _top_type top;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _surface_type;
  _surface_type surface;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _approach_type;
  _approach_type approach;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _binormal_type;
  _binormal_type binormal;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _axis_type;
  _axis_type axis;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _sample_type;
  _sample_type sample;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _width_type;
  _width_type width;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _score_type;
  _score_type score;





  typedef boost::shared_ptr< ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator> const> ConstPtr;

}; // struct GraspConfig_

typedef ::gpd_grasp_msgs::GraspConfig_<std::allocator<void> > GraspConfig;

typedef boost::shared_ptr< ::gpd_grasp_msgs::GraspConfig > GraspConfigPtr;
typedef boost::shared_ptr< ::gpd_grasp_msgs::GraspConfig const> GraspConfigConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator1> & lhs, const ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator2> & rhs)
{
  return lhs.bottom == rhs.bottom &&
    lhs.top == rhs.top &&
    lhs.surface == rhs.surface &&
    lhs.approach == rhs.approach &&
    lhs.binormal == rhs.binormal &&
    lhs.axis == rhs.axis &&
    lhs.sample == rhs.sample &&
    lhs.width == rhs.width &&
    lhs.score == rhs.score;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator1> & lhs, const ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gpd_grasp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e6b3c31591d4b0fc202f092dca68301";
  }

  static const char* value(const ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e6b3c31591d4b0fULL;
  static const uint64_t static_value2 = 0xc202f092dca68301ULL;
};

template<class ContainerAllocator>
struct DataType< ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gpd_grasp_msgs/GraspConfig";
  }

  static const char* value(const ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes a 2-finger grasp configuration by its 6-DOF pose, \n"
"# consisting of a 3-DOF position and 3-DOF orientation, and the opening \n"
"# width of the robot hand.\n"
"\n"
"# Position\n"
"geometry_msgs/Point bottom # centered bottom/base of the robot hand)\n"
"geometry_msgs/Point top # centered top/fingertip of the robot hand)\n"
"geometry_msgs/Point surface # centered position on object surface\n"
"\n"
"# Orientation represented as three axis (R = [approach binormal axis])\n"
"geometry_msgs/Vector3 approach # The grasp approach direction\n"
"geometry_msgs/Vector3 binormal # The binormal\n"
"geometry_msgs/Vector3 axis # The hand axis\n"
"\n"
"geometry_msgs/Point sample # Point at which the grasp was found\n"
"\n"
"std_msgs/Float32 width # Required aperture (opening width) of the robot hand \n"
"\n"
"std_msgs/Float32 score # Score assigned to the grasp by the classifier\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
;
  }

  static const char* value(const ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bottom);
      stream.next(m.top);
      stream.next(m.surface);
      stream.next(m.approach);
      stream.next(m.binormal);
      stream.next(m.axis);
      stream.next(m.sample);
      stream.next(m.width);
      stream.next(m.score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspConfig_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gpd_grasp_msgs::GraspConfig_<ContainerAllocator>& v)
  {
    s << indent << "bottom: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.bottom);
    s << indent << "top: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.top);
    s << indent << "surface: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.surface);
    s << indent << "approach: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.approach);
    s << indent << "binormal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.binormal);
    s << indent << "axis: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.axis);
    s << indent << "sample: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.sample);
    s << indent << "width: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.width);
    s << indent << "score: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPD_GRASP_MSGS_MESSAGE_GRASPCONFIG_H
